---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.application_name }}-audit
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.application_name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.agentConfig.audit_storage_size | default "1Gi" }}
